# Teams Configuration for Jellyfish Status Report Generator
# This file contains configuration for all teams that can generate status reports
# 
# Required fields:
# - jira_project_key: The Jira project key (extracted from team name, no brackets)
# - team_name: Full team name from Jellyfish
# - team_id: Jellyfish team ID
#
# Optional fields:
# - presenter: Name of the presenter (to be filled manually)
# - slide_id: Google Slides slide ID (to be filled manually)
# - image_link: Link to team image file (to be filled manually)

teams:
  # [PRD] Team Ahoy: [AHOY]
  AHOY:
    jira_project_key: "AHOY"
    team_name: "[PRD] Team Ahoy: [AHOY]"
    team_id: 5950
    presenter: ""
    slide_id: ""
    image_link: ""

  # [PRD] Team Altitude: [ALT]
  ALT:
    jira_project_key: "ALT"
    team_name: "[PRD] Team Altitude: [ALT]"
    team_id: 93367
    presenter: ""
    slide_id: ""
    image_link: ""

  # [PRD] The Bumblebees: [BBEE]
  BBEE:
    jira_project_key: "BBEE"
    team_name: "[PRD] The Bumblebees: [BBEE]"
    team_id: 90301
    presenter: ""
    slide_id: ""
    image_link: ""

  # Compliance & Admin Platform: [CAP]
  CAP:
    jira_project_key: "CAP"
    team_name: "Compliance & Admin Platform: [CAP]"
    team_id: 200771
    presenter: ""
    slide_id: ""
    image_link: ""

  # [PRD] Team Content API: [CAPI]
  CAPI:
    jira_project_key: "CAPI"
    team_name: "[PRD] Team Content API: [CAPI]"
    team_id: 61505
    presenter: ""
    slide_id: ""
    image_link: ""

  # [PRD] Isotopes: [CFISO]
  CFISO:
    jira_project_key: "CFISO"
    team_name: "[PRD] Isotopes: [CFISO]"
    team_id: 57210
    presenter: ""
    slide_id: ""
    image_link: ""

  # [PRD] Team Clippy: [CLIP]
  CLIP:
    jira_project_key: "CLIP"
    team_name: "[PRD] Team Clippy: [CLIP]"
    team_id: 210775
    presenter: ""
    slide_id: ""
    image_link: ""

  # [PRD] Team Content Storage: [CSTORE]
  CSTORE:
    jira_project_key: "CSTORE"
    team_name: "[PRD] Team Content Storage: [CSTORE]"
    team_id: 8032
    presenter: ""
    slide_id: ""
    image_link: ""

  # [9T] Development: [DEV]
  DEV:
    jira_project_key: "DEV"
    team_name: "[9T] Development: [DEV]"
    team_id: 184331
    presenter: ""
    slide_id: ""
    image_link: ""

  # [PRD] Team Alpine (Developer Experience)
  DX:
    jira_project_key: "DX"
    team_name: "[PRD] Team Alpine (Developer Experience)"
    team_id: 205723
    presenter: ""
    slide_id: ""
    image_link: ""

  # Ecosystem: [ECO]
  ECO:
    jira_project_key: "ECO"
    team_name: "Ecosystem: [ECO]"
    team_id: 51936
    presenter: ""
    slide_id: ""
    image_link: ""

  # [PRD] Team Tundra (Extensibility)
  EXT:
    jira_project_key: "EXT"
    team_name: "[PRD] Team Tundra (Extensibility)"
    team_id: 5983
    presenter: ""
    slide_id: ""
    image_link: ""

  # [PRD] Fusion: [FUS]
  FUS:
    jira_project_key: "FUS"
    team_name: "[PRD] Fusion: [FUS]"
    team_id: 191503
    presenter: ""
    slide_id: ""
    image_link: ""

  # [PRD] Team Groot: [GROOT]
  GROOT:
    jira_project_key: "GROOT"
    team_name: "[PRD] Team Groot: [GROOT]"
    team_id: 52476
    presenter: ""
    slide_id: ""
    image_link: ""

  # [PRD] Team Hejo: [HEJO]
  HEJO:
    jira_project_key: "HEJO"
    team_name: "[PRD] Team Hejo: [HEJO]"
    team_id: 5952
    presenter: ""
    slide_id: ""
    image_link: ""

  # [PRD] Team Taiga (Marketplace)
  INTEG:
    jira_project_key: "INTEG"
    team_name: "[PRD] Team Taiga (Marketplace)"
    team_id: 65807
    presenter: ""
    slide_id: ""
    image_link: ""

  # [PRD] Team Kraken: [KRK]
  KRK:
    jira_project_key: "KRK"
    team_name: "[PRD] Team Kraken: [KRK]"
    team_id: 10781
    presenter: ""
    slide_id: ""
    image_link: ""

  # [PRD] Mechagodzilla: [MEC]
  MEC:
    jira_project_key: "MEC"
    team_name: "[PRD] Mechagodzilla: [MEC]"
    team_id: 80893
    presenter: ""
    slide_id: ""
    image_link: ""

  # [PRD] Team Mogwai: [MOGWAI]
  MOGWAI:
    jira_project_key: "MOGWAI"
    team_name: "[PRD] Team Mogwai: [MOGWAI]"
    team_id: 11200
    presenter: ""
    slide_id: ""
    image_link: ""

  # [PRD] Team Moi: [MOI]
  MOI:
    jira_project_key: "MOI"
    team_name: "[PRD] Team Moi: [MOI]"
    team_id: 5953
    presenter: ""
    slide_id: ""
    image_link: ""

  # Ninetailed (legacy)
  NINETAILED_LEGACY:
    jira_project_key: ""
    team_name: "Ninetailed (legacy)"
    team_id: 184849
    presenter: ""
    slide_id: ""
    image_link: ""

  # [PRD] Ninetailed: [NT]
  NT:
    jira_project_key: "NT"
    team_name: "[PRD] Ninetailed: [NT]"
    team_id: 186261
    presenter: ""
    slide_id: ""
    image_link: ""

  # Picard: [PIC]
  PIC:
    jira_project_key: "PIC"
    team_name: "Picard: [PIC]"
    team_id: 182737
    presenter: ""
    slide_id: ""
    image_link: ""

  # [PRD] Sparks: [SPA]
  SPA:
    jira_project_key: "SPA"
    team_name: "[PRD] Sparks: [SPA]"
    team_id: 13877
    presenter: ""
    slide_id: ""
    image_link: ""

  # [PRD] Tolkien: [TOL]
  TOL:
    jira_project_key: "TOL"
    team_name: "[PRD] Tolkien: [TOL]"
    team_id: 44743
    presenter: ""
    slide_id: ""
    image_link: ""

  # [PRD] UI Foundation: [UFO]
  UFO:
    jira_project_key: "UFO"
    team_name: "[PRD] UI Foundation: [UFO]"
    team_id: 5947
    presenter: ""
    slide_id: ""
    image_link: ""
